tap "jurplel/tap"

brew "antidote"
brew "bat"
brew "delta"
brew "eza"
brew "fzf"
brew "gh"
brew "lazygit"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "rustup"
brew "scc"
brew "stow"
brew "tldr"
brew "tree-sitter"
brew "yazi"
brew "zig"
brew "zoxide"
brew "hyperfine"

cask "jurplel/tap/instant-space-switcher"
cask "font-hack-nerd-font"
cask "visual-studio-code"
